#
# MAINTAINER        Leejianhao <ljh@ipms.cn>
# DOCKER-VERSION    18.09.2
#
# Dockerizing HelloWorld: Dockerfile for building HelloWorld images
#
FROM       greencloud/tomcat:8.5
MAINTAINER Leejianhao <ljh@ipms.cn>
